### ISSUE TITLE
Allow player prefix and suffix to be given hover text info

### ISSUE THREAD

**Issue by Pugzy** [PGMDev/PGM#603]
### Issue

Servers using custom flairs for ranks and roles make it confusing for new players to understand what each of them are.

Once you know an orange `❖` is the admin staff rank things become easy enough to understand, but providing the players with this info is difficult. Currently, OCC has `/ranks` which helps with this but currently needs to be maintained alongside ranks so they match and players need to know of or be instructed to use the command.

Some servers opt for using the ranks full name as the prefix `[Admin]` but this adds text chat clutter which flairs are designed to remove (especially with longer ranks e.g. `[EventCoordinator]`) and again once you know you know so no need for the constant reminder messing up chat.

### Solution

It would be cool if you could add hover over text to the prefix/suffix to see what they mean.

Perhaps a name, description, and optional link (openable by clicking on the prefix).

![image](https://user-images.githubusercontent.com/8608892/89734559-b65ede00-da54-11ea-8d18-4a993da2047a.png)

These already exist on servers like Hypixel where you can hover over a players `[MVP] Pugzy` to show network level, achievement points, and guild so this is nothing new for players just a "hover to get more info" and exists in PGM on player names for teleporting.

**Comment by applenick** [comment]
Any recommendations for how a clean config layout would look with this added?

For reference current group section: 
```yaml
groups:
  # A special group for server operators.
  op:
    prefix: "&6❖"
```
we also have suffix support now, so would have to be generic enough to apply to each one. 

An idea I had was perhaps being able to define generic flair values under both the `prefix` and `suffix` sections. So in theory could do

```yaml
groups:
  # A special group for server operators.
  op:
    prefix:
        # The actual string for the flair
        flair: '&6❖'
        # Display name used in the hover message 
        display-name: '&6OP'
        # Lore shown in hover message
        description: 'Does admin stuff'
        # Link opened when flair is clicked
        click-link: 'https://oc.tc/staff'      
```
And this format would be the same for suffix (would be identical except prefix would be suffix).

If that’s an acceptable format, I’d be happy to make these changes 👍

**Comment by Pablete1234** [comment]
```yaml
groups:
  mod:
    prefix: '&c❖'
    display-name: 'Moderator'
    description: 'Enforces rules to keep the server clean'
    click-link: 'oc.tc/staff'
```

IMO, that should generate the format of puzgy's screenshot. 
All fields should be optional (if not included, just not shown) and the default formatting should be what pugzy proposed (generic) unless explicitly changed.
Also, no need to make these sub-properties of prefix, have them relative to the group and apply to both prefix and suffix (if they are set)
